<?php

$modelsDir = __DIR__.'/app/Models/';

$models = [
    'Permission' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsToMany;\n\nclass Permission extends Model\n{\n    use HasFactory;\n\n    protected \$guarded = [];\n\n    public function roles(): BelongsToMany\n    {\n        return \$this->belongsToMany(Role::class);\n    }\n\n    public function users(): BelongsToMany\n    {\n        return \$this->belongsToMany(User::class, 'user_permissions')->withPivot('granted_by');\n    }\n}\n",
    'Candidate' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\nuse Illuminate\Database\Eloquent\Relations\HasMany;\n\nclass Candidate extends Model\n{\n    use HasFactory;\n\n    protected \$guarded = [];\n\n    public function user(): BelongsTo\n    {\n        return \$this->belongsTo(User::class);\n    }\n\n    public function workExperiences(): HasMany\n    {\n        return \$this->hasMany(WorkExperience::class);\n    }\n\n    public function skills(): HasMany\n    {\n        return \$this->hasMany(Skill::class);\n    }\n\n    public function educations(): HasMany\n    {\n        return \$this->hasMany(Education::class);\n    }\n\n    public function applications(): HasMany\n    {\n        return \$this->hasMany(Application::class);\n    }\n\n    public function cvAccesses(): HasMany\n    {\n        return \$this->hasMany(CvAccess::class);\n    }\n}\n",
    'Company' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\nuse Illuminate\Database\Eloquent\Relations\HasMany;\n\nclass Company extends Model\n{\n    use HasFactory;\n\n    protected \$guarded = [];\n\n    public function user(): BelongsTo\n    {\n        return \$this->belongsTo(User::class);\n    }\n\n    public function vacancies(): HasMany\n    {\n        return \$this->hasMany(Vacancy::class);\n    }\n}\n",
    'Vacancy' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\nuse Illuminate\Database\Eloquent\Relations\HasMany;\n\nclass Vacancy extends Model\n{\n    use HasFactory;\n\n    protected \$guarded = [];\n\n    public function company(): BelongsTo\n    {\n        return \$this->belongsTo(Company::class);\n    }\n\n    public function applications(): HasMany\n    {\n        return \$this->hasMany(Application::class);\n    }\n}\n",
    'WorkExperience' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass WorkExperience extends Model\n{\n    use HasFactory;\n\n    protected \$table = 'work_experiencies';\n    protected \$guarded = [];\n\n    public function candidate(): BelongsTo\n    {\n        return \$this->belongsTo(Candidate::class);\n    }\n}\n",
    'Skill' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass Skill extends Model\n{\n    use HasFactory;\n\n    protected \$guarded = [];\n\n    public function candidate(): BelongsTo\n    {\n        return \$this->belongsTo(Candidate::class);\n    }\n}\n",
    'Education' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass Education extends Model\n{\n    use HasFactory;\n\n    protected \$guarded = [];\n\n    public function candidate(): BelongsTo\n    {\n        return \$this->belongsTo(Candidate::class);\n    }\n}\n",
    'Application' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\nuse Illuminate\Database\Eloquent\Relations\HasMany;\n\nclass Application extends Model\n{\n    use HasFactory;\n\n    protected \$guarded = [];\n\n    public function candidate(): BelongsTo\n    {\n        return \$this->belongsTo(Candidate::class);\n    }\n\n    public function vacancy(): BelongsTo\n    {\n        return \$this->belongsTo(Vacancy::class);\n    }\n\n    public function cvAccesses(): HasMany\n    {\n        return \$this->hasMany(CvAccess::class);\n    }\n}\n",
    'CvAccess' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass CvAccess extends Model\n{\n    use HasFactory;\n\n    protected \$guarded = [];\n\n    public function candidate(): BelongsTo\n    {\n        return \$this->belongsTo(Candidate::class);\n    }\n\n    public function accessedBy(): BelongsTo\n    {\n        return \$this->belongsTo(User::class, 'accessed_by');\n    }\n\n    public function application(): BelongsTo\n    {\n        return \$this->belongsTo(Application::class);\n    }\n}\n",
    'AuditLog' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass AuditLog extends Model\n{\n    use HasFactory;\n\n    protected \$guarded = [];\n\n    public function user(): BelongsTo\n    {\n        return \$this->belongsTo(User::class);\n    }\n}\n",
    'Incident' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\nuse Illuminate\Database\Eloquent\Relations\HasMany;\n\nclass Incident extends Model\n{\n    use HasFactory;\n\n    protected \$guarded = [];\n\n    public function affectedUser(): BelongsTo\n    {\n        return \$this->belongsTo(User::class, 'affected_user_id');\n    }\n\n    public function incidentActions(): HasMany\n    {\n        return \$this->hasMany(IncidentAction::class);\n    }\n}\n",
    'IncidentAction' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass IncidentAction extends Model\n{\n    use HasFactory;\n\n    protected \$guarded = [];\n\n    public function incident(): BelongsTo\n    {\n        return \$this->belongsTo(Incident::class);\n    }\n\n    public function performedBy(): BelongsTo\n    {\n        return \$this->belongsTo(User::class, 'performed_by');\n    }\n}\n",
    'SystemAlert' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass SystemAlert extends Model\n{\n    use HasFactory;\n\n    protected \$guarded = [];\n\n    public function user(): BelongsTo\n    {\n        return \$this->belongsTo(User::class);\n    }\n\n    public function reviewedBy(): BelongsTo\n    {\n        return \$this->belongsTo(User::class, 'reviewed_by');\n    }\n}\n",
    'BackupLog' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass BackupLog extends Model\n{\n    use HasFactory;\n\n    protected \$guarded = [];\n\n    public function executedBy(): BelongsTo\n    {\n        return \$this->belongsTo(User::class, 'executed_by');\n    }\n}\n",
    'Training' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\nuse Illuminate\Database\Eloquent\Relations\BelongsToMany;\nuse Illuminate\Database\Eloquent\Relations\HasMany;\n\nclass Training extends Model\n{\n    use HasFactory;\n\n    protected \$guarded = [];\n\n    public function targetRole(): BelongsTo\n    {\n        return \$this->belongsTo(Role::class, 'target_role_id');\n    }\n\n    public function users(): BelongsToMany\n    {\n        return \$this->belongsToMany(User::class, 'user_trainings');\n    }\n\n    public function userTrainings(): HasMany\n    {\n        return \$this->hasMany(UserTraining::class);\n    }\n}\n",
    'UserTraining' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass UserTraining extends Model\n{\n    use HasFactory;\n\n    protected \$guarded = [];\n\n    public function user(): BelongsTo\n    {\n        return \$this->belongsTo(User::class);\n    }\n\n    public function training(): BelongsTo\n    {\n        return \$this->belongsTo(Training::class);\n    }\n}\n",
    'PasswordHistory' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass PasswordHistory extends Model\n{\n    use HasFactory;\n\n    protected \$guarded = [];\n\n    public function user(): BelongsTo\n    {\n        return \$this->belongsTo(User::class);\n    }\n}\n",
    'LoginAttempt' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass LoginAttempt extends Model\n{\n    use HasFactory;\n\n    protected \$guarded = [];\n\n    public function user(): BelongsTo\n    {\n        return \$this->belongsTo(User::class);\n    }\n}\n",
];

foreach ($models as $name => $content) {
    file_put_contents($modelsDir.$name.'.php', $content);
}
